base_url = "https://vynwg.com"

title = "Vynwg"
description = "Vinícius W's personal page"
author = "Vinícius W."
theme = "tabi"


generate_feed = true
compile_sass = true
minify_html = true

build_search_index = false
taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[extra]
theme_switcher = true
default_theme = ""
skin = "mint"

browser_theme_color = "#087e96"
stylesheets = []

base_canonical_url = "https://vynwg.com"

remote_repository_url = "https://github.com/vynwg/vynwg.com"
remote_repository_git_platform = "auto"
remote_repository_branch = "master"
show_remote_changes = true
show_remote_source = true

copy_button = true

show_reading_time = false
footnote_backlinks = false

katex = false
quick_navigation_buttons = false
toc = false
long_date_format = "%d %B %Y"

short_date_format = "%-d %B %Y"

separator = "|"
invert_title_order = false

favicon = "/favicon.svg"
favicon_emoji = "🌱"

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
]

feed_icon = false
full_content_in_feed = false

email = "dmluaWNpdXNAdnlud2cuY29t"
encode_plaintext_email = false

socials = [
    { name = "github", url = "https://github.com/vynwg/", icon = "github" },
    { name = "instagram", url = "https://instagram.com/vyn.wg", icon = "instagram" },
]

footer_menu = [
    {url = "about", name = "about", trailing_slash = true},
    {url = "privacy", name = "privacy", trailing_slash = true},
    {url = "sitemap.xml", name = "sitemap", trailing_slash = false},
]

allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'"] },
    { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com"] },
]

custom_subset = true
